/*
 * File: PhotonOnlineWaveCombatSyncManager.cs
 *
 * Purpose:
 * Implements master-authoritative online enemy wave and combat synchronization for CanalTD.
 *
 * Attached GameObject:
 * Online scene managers or networking helper objects used during the Photon GameScene flow.
 *
 * Main responsibilities:
 * - Start and end online enemy waves from the MasterClient.
 * - Synchronize enemy spawn, movement, HP, death, castle damage, and reward updates.
 * - Guard non-master clients from applying permanent combat results locally.
 * - Provide diagnostics for duplicate enemies, host migration, and invalid online wave state.
 *
 * Inputs:
 * - Photon room/player state and network events.
 * - Runtime wave, enemy, castle, tower, and player-resource state from GameScene.
 * - MasterClient combat outcomes generated by the existing local gameplay systems.
 *
 * Outputs or effects:
 * - Broadcasts authoritative online wave/combat payloads to all clients.
 * - Applies synchronized enemy, castle, reward, wave, and UI feedback state.
 * - Keeps Local mode, AI mode, and GuideScene outside this online-only synchronization path.
 *
 * Authorship or assistance:
 * - Core gameplay design, Unity setup, and project integration were developed by Jingyu Pan.
 * - This online synchronization helper was added with AI assistance for the Photon online extension.
 *
 * Testing notes:
 * - Retest 2-player and 4-player room-code online matches after editing this script.
 * - Verify wave start, enemy spawn, enemy death, rewards, castle damage, wave end, and host migration.
 */
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

#if PHOTON_UNITY_NETWORKING
using ExitGames.Client.Photon;
using Photon.Pun;
using Photon.Realtime;
#endif

#if PHOTON_UNITY_NETWORKING
public class PhotonOnlineWaveCombatSyncManager : MonoBehaviourPunCallbacks, IOnEventCallback
#else
public class PhotonOnlineWaveCombatSyncManager : MonoBehaviour
#endif
{
    private const byte WaveStartEventCode = 31;
    private const byte EnemyPositionEventCode = 32;
    private const byte EnemyHealthEventCode = 33;
    private const byte EnemyKilledEventCode = 34;
    private const byte CastleDamageEventCode = 35;
    private const byte RewardEventCode = 36;
    private const byte WaveEndEventCode = 37;

    public static PhotonOnlineWaveCombatSyncManager Instance { get; private set; }

    [Header("Managers")]
    public PhotonOnlineGameSceneManager onlineGameSceneManager;
    public GamePhaseManager gamePhaseManager;
    public WaveManager waveManager;
    public PlayerManager playerManager;

    [Header("Sync Settings")]
    public float spawnIntervalSeconds = 0.5f;
    public float positionSyncIntervalSeconds = 0.25f;
    public float waveEndDelaySeconds = 1.0f;

    private readonly Dictionary<string, OnlineEnemyIdentity> enemiesById = new Dictionary<string, OnlineEnemyIdentity>();
    private readonly Dictionary<string, EnemySpawner> spawnersById = new Dictionary<string, EnemySpawner>();
    private bool initialized;
    private bool onlineWaveRunning;
    private bool onlineWaveSpawning;
    private bool waveEndPending;
    private int activeWaveIndex = 1;
    private int activeRound = 1;
    private Coroutine spawnRoutine;
    private float lastPositionSyncTime;

    public bool IsOnlineWaveRunning
    {
        get { return onlineWaveRunning; }
    }

    /// <summary>
    /// Finds and stores Photon online wave combat sync manager references before scene gameplay begins.
    /// </summary>
    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
        AutoAssignReferences();
    }

    /// <summary>
    /// Subscribes Photon online wave combat sync manager to the events it needs while enabled.
    /// </summary>
    private void OnEnable()
    {
#if PHOTON_UNITY_NETWORKING
        PhotonNetwork.AddCallbackTarget(this);
#endif
    }

    /// <summary>
    /// Unsubscribes Photon online wave combat sync manager from events so disabled objects stop receiving callbacks.
    /// </summary>
    private void OnDisable()
    {
#if PHOTON_UNITY_NETWORKING
        PhotonNetwork.RemoveCallbackTarget(this);
#endif

        if (Instance == this)
        {
            Instance = null;
        }
    }

    /// <summary>
    /// Checks Photon online wave combat sync manager input, timing, animation, or UI state once per frame.
    /// </summary>
    private void Update()
    {
#if PHOTON_UNITY_NETWORKING
        if (!CanRunOnlineWaveSync() || !onlineWaveRunning || !PhotonNetwork.IsMasterClient)
        {
            return;
        }

        if (Time.time - lastPositionSyncTime >= positionSyncIntervalSeconds)
        {
            lastPositionSyncTime = Time.time;
            BroadcastEnemyPositions();
        }

        if (!onlineWaveSpawning && !waveEndPending && AreAllOnlineEnemiesResolved())
        {
            StartCoroutine(EndWaveAfterDelay());
        }
#endif
    }

    /// <summary>
    /// Prepares this manager for a Photon match and loads or sends the starting synchronized state.
    /// </summary>
    public void InitializeForOnlineMatch()
    {
        AutoAssignReferences();
        initialized = CanRunOnlineWaveSync();
        RebuildSpawnerRegistry();
        RebuildEnemyRegistryFromScene("InitializeForOnlineMatch");
    }

    /// <summary>
    /// Attempts to start wave as master and returns false if rules, resources, or references block it.
    /// </summary>
    public bool TryStartWaveAsMaster(int round, int waveIndex)
    {
#if !PHOTON_UNITY_NETWORKING
        return false;
#else
        if (!CanRunOnlineWaveSync() || !PhotonNetwork.IsMasterClient || onlineWaveRunning)
        {
            Debug.LogWarning(
                "OnlineWaveStart rejected. canRun=" + CanRunOnlineWaveSync() +
                ", isMaster=" + PhotonNetwork.IsMasterClient +
                ", onlineWaveRunning=" + onlineWaveRunning +
                ", round=" + round +
                ", waveIndex=" + waveIndex
            );
            return false;
        }

        AutoAssignReferences();
        RebuildSpawnerRegistry();

        int safeRound = Mathf.Max(1, round);
        int safeWaveIndex = Mathf.Max(1, waveIndex);
        int enemyCount = waveManager != null ? waveManager.GetOnlineEnemyCountForRound(safeWaveIndex) : 0;
        List<GameObject> spawnPrefabs = waveManager != null
            ? waveManager.BuildOnlineEnemySpawnPlan(safeWaveIndex, enemyCount)
            : new List<GameObject>();

        OnlineWaveStartData waveData = new OnlineWaveStartData
        {
            round = safeRound,
            waveIndex = safeWaveIndex,
            enemyCount = enemyCount,
            spawnEntries = new List<OnlineEnemySpawnData>()
        };

        EnemySpawner[] spawners = waveManager != null ? waveManager.spawners : null;
        int spawnerCount = spawners != null ? spawners.Length : 0;

        for (int i = 0; i < enemyCount; i++)
        {
            EnemySpawner spawner = spawnerCount > 0 ? spawners[i % spawnerCount] : null;
            GameObject prefab = spawnPrefabs != null && i < spawnPrefabs.Count ? spawnPrefabs[i] : null;
            string enemyTypeId = prefab != null ? prefab.name : "EnemySpawnerFallback";
            string spawnPointId = spawner != null ? spawner.name : string.Empty;
            string enemyId = "R" + safeRound + "_W" + safeWaveIndex + "_E" + i;

            waveData.spawnEntries.Add(new OnlineEnemySpawnData
            {
                enemyId = enemyId,
                enemyTypeId = enemyTypeId,
                spawnPointId = spawnPointId,
                spawnOrder = i,
                spawnTime = i * spawnIntervalSeconds
            });

            Debug.Log(
                "OnlineSpawnEnemy" +
                " enemyId=" + enemyId +
                " enemyType=" + enemyTypeId +
                " spawnPointId=" + spawnPointId +
                " round=" + safeRound +
                " waveIndex=" + safeWaveIndex
            );
        }

        Debug.Log("OnlineWaveStart round=" + safeRound + " waveIndex=" + safeWaveIndex + " enemyCount=" + enemyCount);
        RaiseToAll(WaveStartEventCode, waveData);
        return true;
#endif
    }

    /// <summary>
    /// Decides whether should block local enemy damage should happen in the current mode and turn state.
    /// </summary>
    public static bool ShouldBlockLocalEnemyDamage()
    {
#if PHOTON_UNITY_NETWORKING
        return PhotonOnlineGameSceneManager.IsLiveOnlineGameSceneContext() &&
            PhotonNetwork.InRoom &&
            !PhotonNetwork.OfflineMode &&
            !PhotonNetwork.IsMasterClient;
#else
        return false;
#endif
    }

    /// <summary>
    /// Decides whether should block local castle damage should happen in the current mode and turn state.
    /// </summary>
    public static bool ShouldBlockLocalCastleDamage()
    {
        /// <summary>
        /// Handles should block local enemy damage for Photon online wave combat sync manager.
        /// </summary>
        return ShouldBlockLocalEnemyDamage();
    }

    /// <summary>
    /// Notifies connected systems that enemy damaged by master occurred.
    /// </summary>
    public static void NotifyEnemyDamagedByMaster(EnemyHealth enemy, int damage, PlayerResource damageOwner)
    {
#if PHOTON_UNITY_NETWORKING
        if (Instance == null || !PhotonNetwork.IsMasterClient || enemy == null)
        {
            return;
        }

        Instance.BroadcastEnemyHealth(enemy, damage, damageOwner);
#endif
    }

    /// <summary>
    /// Notifies connected systems that enemy killed by master occurred.
    /// </summary>
    public static void NotifyEnemyKilledByMaster(EnemyHealth enemy, PlayerResource rewardOwner)
    {
#if PHOTON_UNITY_NETWORKING
        if (Instance == null || !PhotonNetwork.IsMasterClient || enemy == null)
        {
            return;
        }

        Instance.BroadcastEnemyKilled(enemy, rewardOwner);
#endif
    }

    /// <summary>
    /// Notifies connected systems that enemy resolved at castle by master occurred.
    /// </summary>
    public static void NotifyEnemyResolvedAtCastleByMaster(GameObject enemy, CastleBase castle)
    {
#if PHOTON_UNITY_NETWORKING
        if (Instance == null || !PhotonNetwork.IsMasterClient || enemy == null)
        {
            return;
        }

        EnemyHealth health = enemy.GetComponent<EnemyHealth>();

        if (health != null)
        {
            Instance.BroadcastEnemyKilled(health, null);
        }
#endif
    }

    /// <summary>
    /// Notifies connected systems that castle damaged by master occurred.
    /// </summary>
    public static void NotifyCastleDamagedByMaster(CastleBase castle, int damage)
    {
#if PHOTON_UNITY_NETWORKING
        if (Instance == null || !PhotonNetwork.IsMasterClient || castle == null)
        {
            return;
        }

        Instance.BroadcastCastleDamage(castle, damage);
#endif
    }

    /// <summary>
    /// Notifies connected systems that reward granted by master occurred.
    /// </summary>
    public static void NotifyRewardGrantedByMaster(PlayerResource player)
    {
#if PHOTON_UNITY_NETWORKING
        if (Instance == null || !PhotonNetwork.IsMasterClient || player == null)
        {
            return;
        }

        Instance.BroadcastReward(player);
#endif
    }

#if PHOTON_UNITY_NETWORKING
    /// <summary>
    /// Responds to on event and updates the affected gameplay or UI systems.
    /// </summary>
    public void OnEvent(EventData photonEvent)
    {
        if (!CanRunOnlineWaveSync())
        {
            return;
        }

        string json = photonEvent.CustomData as string;

        if (photonEvent.Code == WaveStartEventCode)
        {
            ApplyWaveStart(JsonUtility.FromJson<OnlineWaveStartData>(json));
        }
        else if (photonEvent.Code == EnemyPositionEventCode)
        {
            ApplyEnemyPositions(JsonUtility.FromJson<OnlineEnemyPositionBatchData>(json));
        }
        else if (photonEvent.Code == EnemyHealthEventCode)
        {
            ApplyEnemyHealth(JsonUtility.FromJson<OnlineEnemyHealthData>(json));
        }
        else if (photonEvent.Code == EnemyKilledEventCode)
        {
            ApplyEnemyKilled(JsonUtility.FromJson<OnlineEnemyKilledData>(json));
        }
        else if (photonEvent.Code == CastleDamageEventCode)
        {
            ApplyCastleDamage(JsonUtility.FromJson<OnlineCastleDamageData>(json));
        }
        else if (photonEvent.Code == RewardEventCode)
        {
            ApplyReward(JsonUtility.FromJson<OnlineRewardData>(json));
        }
        else if (photonEvent.Code == WaveEndEventCode)
        {
            ApplyWaveEnd(JsonUtility.FromJson<OnlineWaveEndData>(json));
        }
    }

    /// <summary>
    /// Responds to on player left room and updates the affected gameplay or UI systems.
    /// </summary>
    public override void OnPlayerLeftRoom(Player otherPlayer)
    {
        if (!CanRunOnlineWaveSync())
        {
            return;
        }

        Debug.Log("Online wave player leave observed. actor=" + otherPlayer.ActorNumber + ", isMaster=" + PhotonNetwork.IsMasterClient + ", waveRunning=" + onlineWaveRunning + ".");
        RebuildEnemyRegistryFromScene("OnPlayerLeftRoom");
    }

    /// <summary>
    /// Responds to on master client switched and updates the affected gameplay or UI systems.
    /// </summary>
    public override void OnMasterClientSwitched(Player newMasterClient)
    {
        if (!CanRunOnlineWaveSync())
        {
            return;
        }

        Debug.Log("Online wave MasterClient switched. newActor=" + newMasterClient.ActorNumber + ", localIsMaster=" + PhotonNetwork.IsMasterClient + ", waveRunning=" + onlineWaveRunning + ".");
        RebuildEnemyRegistryFromScene("OnMasterClientSwitched");

        if (PhotonNetwork.IsMasterClient && onlineWaveRunning && !onlineWaveSpawning && !waveEndPending && AreAllOnlineEnemiesResolved())
        {
            StartCoroutine(EndWaveAfterDelay());
        }
    }
#endif

    /// <summary>
    /// Applies synchronized wave start to this client so it matches the authoritative state.
    /// </summary>
    private void ApplyWaveStart(OnlineWaveStartData waveData)
    {
        if (waveData == null)
        {
            return;
        }

        AutoAssignReferences();
        RebuildSpawnerRegistry();
        ClearOnlineEnemies();

        onlineWaveRunning = true;
        onlineWaveSpawning = true;
        activeRound = Mathf.Max(1, waveData.round);
        activeWaveIndex = Mathf.Max(1, waveData.waveIndex);

        if (gamePhaseManager != null)
        {
            gamePhaseManager.currentPhase = GamePhase.WavePhase;
            gamePhaseManager.currentRound = activeRound;
            gamePhaseManager.currentWaveIndex = activeWaveIndex;
        }

        waveManager?.ApplyOnlineWaveStarted(activeWaveIndex);
        NotifyTowersWaveStarted();
        NotifyShockTrapsWaveStarted();
        CurrentTurnIndicatorManager.Instance?.HideAllMarkers();
        ShowOnlineToast("Enemy Wave Started");

        if (spawnRoutine != null)
        {
            StopCoroutine(spawnRoutine);
        }

        waveEndPending = false;
        spawnRoutine = StartCoroutine(SpawnOnlineWaveRoutine(waveData));
    }

    /// <summary>
    /// Spawns online wave routine into the scene and initializes its runtime state.
    /// </summary>
    private IEnumerator SpawnOnlineWaveRoutine(OnlineWaveStartData waveData)
    {
        if (EnemyPathAssignmentManager.Instance != null && waveManager != null)
        {
            EnemyPathAssignmentManager.Instance.ResetAssignmentsForWave(waveData.enemyCount, waveManager.spawners);
        }

        List<OnlineEnemySpawnData> entries = waveData.spawnEntries ?? new List<OnlineEnemySpawnData>();

        for (int i = 0; i < entries.Count; i++)
        {
            SpawnOnlineEnemy(entries[i], waveData.round, waveData.waveIndex);
            /// <summary>
            /// Handles wait for seconds for Photon online wave combat sync manager.
            /// </summary>
            yield return new WaitForSeconds(spawnIntervalSeconds);
        }

        onlineWaveSpawning = false;
        spawnRoutine = null;
    }

    /// <summary>
    /// Spawns online enemy into the scene and initializes its runtime state.
    /// </summary>
    private void SpawnOnlineEnemy(OnlineEnemySpawnData spawnData, int round, int waveIndex)
    {
        if (spawnData == null)
        {
            return;
        }

        if (enemiesById.ContainsKey(spawnData.enemyId))
        {
            Debug.LogWarning("Duplicate enemy detection: online enemy id already exists before spawn. enemyId=" + spawnData.enemyId);
            return;
        }

        EnemySpawner spawner = ResolveSpawner(spawnData.spawnPointId);

        if (spawner == null)
        {
            Debug.LogWarning("OnlineSpawnEnemy failed: missing spawnPointId=" + spawnData.spawnPointId);
            return;
        }

        GameObject prefab = waveManager != null ? waveManager.ResolveOnlineEnemyPrefab(spawnData.enemyTypeId) : null;
        GameObject enemy = spawner.SpawnOne(prefab, round, waveManager != null ? waveManager.hpScalePerRound : 0f, waveManager != null ? waveManager.speedScalePerRound : 0f);

        if (enemy == null)
        {
            return;
        }

        OnlineEnemyIdentity identity = enemy.GetComponent<OnlineEnemyIdentity>();
        if (identity == null)
        {
            identity = enemy.AddComponent<OnlineEnemyIdentity>();
        }

        identity.enemyId = spawnData.enemyId;
        identity.enemyTypeId = spawnData.enemyTypeId;
        identity.spawnOrder = spawnData.spawnOrder;
        identity.round = round;
        enemiesById[identity.enemyId] = identity;

        Debug.Log(
            "OnlineSpawnEnemy" +
            " enemyId=" + identity.enemyId +
            " enemyType=" + identity.enemyTypeId +
            " spawnPointId=" + spawnData.spawnPointId +
            " round=" + round +
            " waveIndex=" + waveIndex
        );
    }

    /// <summary>
    /// Coordinates broadcast enemy positions for Photon synchronization and local scene state.
    /// </summary>
    private void BroadcastEnemyPositions()
    {
#if PHOTON_UNITY_NETWORKING
        OnlineEnemyPositionBatchData batch = new OnlineEnemyPositionBatchData
        {
            round = activeRound,
            waveIndex = activeWaveIndex,
            enemies = new List<OnlineEnemyPositionData>()
        };

        foreach (KeyValuePair<string, OnlineEnemyIdentity> pair in enemiesById)
        {
            if (pair.Value == null)
            {
                continue;
            }

            Vector3 position = pair.Value.transform.position;
            batch.enemies.Add(new OnlineEnemyPositionData
            {
                enemyId = pair.Key,
                x = position.x,
                y = position.y,
                z = position.z
            });
        }

        if (batch.enemies.Count > 0)
        {
            Debug.Log("OnlineEnemyMove round=" + activeRound + " waveIndex=" + activeWaveIndex + " count=" + batch.enemies.Count);
            RaiseToAll(EnemyPositionEventCode, batch);
        }
#endif
    }

    /// <summary>
    /// Coordinates broadcast enemy health for Photon synchronization and local scene state.
    /// </summary>
    private void BroadcastEnemyHealth(EnemyHealth enemy, int damage, PlayerResource damageOwner)
    {
        OnlineEnemyIdentity identity = enemy.GetComponent<OnlineEnemyIdentity>();

        if (identity == null || string.IsNullOrWhiteSpace(identity.enemyId))
        {
            return;
        }

        OnlineEnemyHealthData data = new OnlineEnemyHealthData
        {
            enemyId = identity.enemyId,
            enemyTypeId = identity.enemyTypeId,
            currentHP = enemy.CurrentHP,
            maxHP = enemy.MaxHP,
            damage = damage,
            damageOwnerPlayerId = damageOwner != null ? damageOwner.playerId : -1,
            round = activeRound,
            waveIndex = activeWaveIndex
        };

        Debug.Log(
            "OnlineEnemyDamaged enemyId=" + data.enemyId +
            " enemyType=" + data.enemyTypeId +
            " currentHP=" + data.currentHP +
            " damage=" + data.damage +
            " round=" + data.round +
            " waveIndex=" + data.waveIndex
        );
        RaiseToAll(EnemyHealthEventCode, data);
    }

    /// <summary>
    /// Coordinates broadcast enemy killed for Photon synchronization and local scene state.
    /// </summary>
    private void BroadcastEnemyKilled(EnemyHealth enemy, PlayerResource rewardOwner)
    {
        OnlineEnemyIdentity identity = enemy.GetComponent<OnlineEnemyIdentity>();

        if (identity == null || string.IsNullOrWhiteSpace(identity.enemyId))
        {
            return;
        }

        OnlineEnemyKilledData data = new OnlineEnemyKilledData
        {
            enemyId = identity.enemyId,
            enemyTypeId = identity.enemyTypeId,
            rewardPlayerId = rewardOwner != null ? rewardOwner.playerId : -1,
            round = activeRound,
            waveIndex = activeWaveIndex
        };

        Debug.Log(
            "OnlineEnemyKilled enemyId=" + data.enemyId +
            " enemyType=" + data.enemyTypeId +
            " rewardPlayerId=" + data.rewardPlayerId +
            " round=" + data.round +
            " waveIndex=" + data.waveIndex
        );
        RaiseToAll(EnemyKilledEventCode, data);
    }

    /// <summary>
    /// Coordinates broadcast castle damage for Photon synchronization and local scene state.
    /// </summary>
    private void BroadcastCastleDamage(CastleBase castle, int damage)
    {
        OnlineCastleDamageData data = new OnlineCastleDamageData
        {
            targetPlayerId = castle.GetOwnerPlayerId(),
            currentHP = castle.GetCurrentHP(),
            maxHP = castle.GetMaxHP(),
            damage = damage,
            round = activeRound,
            waveIndex = activeWaveIndex
        };

        Debug.Log(
            "OnlineCastleDamaged targetCastle/playerId=" + data.targetPlayerId +
            " damage=" + data.damage +
            " currentHP=" + data.currentHP +
            " round=" + data.round +
            " waveIndex=" + data.waveIndex
        );
        RaiseToAll(CastleDamageEventCode, data);
    }

    /// <summary>
    /// Coordinates broadcast reward for Photon synchronization and local scene state.
    /// </summary>
    private void BroadcastReward(PlayerResource player)
    {
        OnlineRewardData data = new OnlineRewardData
        {
            rewardPlayerId = player.playerId,
            gold = player.money,
            score = player.score,
            round = activeRound,
            waveIndex = activeWaveIndex
        };

        Debug.Log(
            "OnlineRewardGranted rewardPlayerId=" + data.rewardPlayerId +
            " gold=" + data.gold +
            " score=" + data.score +
            " round=" + data.round +
            " waveIndex=" + data.waveIndex
        );
        RaiseToAll(RewardEventCode, data);
    }

    /// <summary>
    /// Coordinates end wave after delay for Photon synchronization and local scene state.
    /// </summary>
    private IEnumerator EndWaveAfterDelay()
    {
        if (waveEndPending)
        {
            yield break;
        }

        waveEndPending = true;
        onlineWaveSpawning = true;
        /// <summary>
        /// Handles wait for seconds for Photon online wave combat sync manager.
        /// </summary>
        yield return new WaitForSeconds(waveEndDelaySeconds);

        if (!AreAllOnlineEnemiesResolved())
        {
            onlineWaveSpawning = false;
            waveEndPending = false;
            yield break;
        }

        int nextRound = activeRound + 1;
        OnlineWaveEndData data = new OnlineWaveEndData
        {
            round = activeRound,
            waveIndex = activeWaveIndex,
            nextRound = nextRound
        };

        Debug.Log("OnlineWaveEnd round=" + activeRound + " waveIndex=" + activeWaveIndex + " nextRound=" + nextRound);
        RaiseToAll(WaveEndEventCode, data);

        if (onlineGameSceneManager != null)
        {
            onlineGameSceneManager.BeginNextOnlineRoundAfterWaveAsMaster(nextRound);
        }
    }

    /// <summary>
    /// Applies synchronized enemy positions to this client so it matches the authoritative state.
    /// </summary>
    private void ApplyEnemyPositions(OnlineEnemyPositionBatchData batch)
    {
        if (batch == null || batch.enemies == null)
        {
            return;
        }

        for (int i = 0; i < batch.enemies.Count; i++)
        {
            OnlineEnemyPositionData positionData = batch.enemies[i];

            if (positionData == null || !enemiesById.TryGetValue(positionData.enemyId, out OnlineEnemyIdentity identity) || identity == null)
            {
                continue;
            }

            if (ShouldBlockLocalEnemyDamage())
            {
                identity.transform.position = new Vector3(positionData.x, positionData.y, positionData.z);
            }
        }
    }

    /// <summary>
    /// Applies synchronized enemy health to this client so it matches the authoritative state.
    /// </summary>
    private void ApplyEnemyHealth(OnlineEnemyHealthData data)
    {
        if (data == null || !enemiesById.TryGetValue(data.enemyId, out OnlineEnemyIdentity identity) || identity == null)
        {
            return;
        }

        EnemyHealth enemy = identity.GetComponent<EnemyHealth>();
        enemy?.ApplyOnlineHealthState(data.currentHP, data.maxHP);
    }

    /// <summary>
    /// Applies synchronized enemy killed to this client so it matches the authoritative state.
    /// </summary>
    private void ApplyEnemyKilled(OnlineEnemyKilledData data)
    {
        if (data == null || !enemiesById.TryGetValue(data.enemyId, out OnlineEnemyIdentity identity) || identity == null)
        {
            return;
        }

        EnemyHealth enemy = identity.GetComponent<EnemyHealth>();
        enemy?.ApplyOnlineKilledState();
        enemiesById.Remove(data.enemyId);
    }

    /// <summary>
    /// Applies synchronized castle damage to this client so it matches the authoritative state.
    /// </summary>
    private void ApplyCastleDamage(OnlineCastleDamageData data)
    {
        if (data == null)
        {
            return;
        }

        CastleBase castle = ResolveCastleByPlayerId(data.targetPlayerId);
        castle?.ApplyOnlineHealthState(data.currentHP);
    }

    /// <summary>
    /// Applies synchronized reward to this client so it matches the authoritative state.
    /// </summary>
    private void ApplyReward(OnlineRewardData data)
    {
        if (data == null || playerManager == null)
        {
            return;
        }

        PlayerResource player = playerManager.GetPlayerResource(data.rewardPlayerId);

        if (player == null)
        {
            return;
        }

        player.money = data.gold;
        player.score = data.score;
        player.RefreshUI();
        playerManager.RefreshAllPlayerStatusPanels();
    }

    /// <summary>
    /// Applies synchronized wave end to this client so it matches the authoritative state.
    /// </summary>
    private void ApplyWaveEnd(OnlineWaveEndData data)
    {
        onlineWaveRunning = false;
        onlineWaveSpawning = false;
        waveEndPending = false;
        ClearOnlineEnemies();
        int nextRound = data != null ? data.nextRound : activeRound + 1;
        NotifyTowersWaveEnded();
        NotifyShockTrapsWaveEnded();
        waveManager?.ApplyOnlineWaveEnded(nextRound);
        ShowOnlineToast("Enemy Wave Cleared");
    }

    private void NotifyTowersWaveStarted()
    {
        foreach (CannonTower tower in FindObjectsOfType<CannonTower>())
        {
            if (tower != null)
            {
                tower.OnWaveStarted();
            }
        }
    }

    private void NotifyTowersWaveEnded()
    {
        foreach (CannonTower tower in FindObjectsOfType<CannonTower>())
        {
            if (tower != null)
            {
                tower.OnWaveEnded();
            }
        }
    }

    private void NotifyShockTrapsWaveStarted()
    {
        foreach (ShockTrap trap in FindObjectsOfType<ShockTrap>())
        {
            if (trap != null)
            {
                trap.OnWaveStarted();
            }
        }
    }

    private void NotifyShockTrapsWaveEnded()
    {
        foreach (ShockTrap trap in FindObjectsOfType<ShockTrap>())
        {
            if (trap != null)
            {
                trap.OnWaveEnded();
            }
        }
    }

    /// <summary>
    /// Coordinates are all online enemies resolved for Photon synchronization and local scene state.
    /// </summary>
    private bool AreAllOnlineEnemiesResolved()
    {
        List<string> staleIds = new List<string>();

        foreach (KeyValuePair<string, OnlineEnemyIdentity> pair in enemiesById)
        {
            if (pair.Value == null)
            {
                staleIds.Add(pair.Key);
            }
        }

        foreach (string staleId in staleIds)
        {
            enemiesById.Remove(staleId);
        }

        return enemiesById.Count == 0;
    }

    /// <summary>
    /// Clears online enemies and removes its temporary gameplay or visual effect.
    /// </summary>
    private void ClearOnlineEnemies()
    {
        enemiesById.Clear();
    }

    /// <summary>
    /// Rebuilds enemy registry from scene from current scene objects or synchronized data.
    /// </summary>
    private void RebuildEnemyRegistryFromScene(string context)
    {
        enemiesById.Clear();
        OnlineEnemyIdentity[] identities = FindObjectsOfType<OnlineEnemyIdentity>();

        foreach (OnlineEnemyIdentity identity in identities)
        {
            if (identity == null || string.IsNullOrWhiteSpace(identity.enemyId))
            {
                continue;
            }

            if (enemiesById.ContainsKey(identity.enemyId))
            {
                Debug.LogWarning("Duplicate enemy detection during " + context + ": enemyId=" + identity.enemyId + ".");
                continue;
            }

            enemiesById.Add(identity.enemyId, identity);
        }

        Debug.Log("Online enemy registry rebuilt during " + context + ". count=" + enemiesById.Count + ", waveRunning=" + onlineWaveRunning + ".");
    }

    /// <summary>
    /// Coordinates auto assign references for Photon synchronization and local scene state.
    /// </summary>
    private void AutoAssignReferences()
    {
        if (onlineGameSceneManager == null)
        {
            onlineGameSceneManager = PhotonOnlineGameSceneManager.Instance != null
                ? PhotonOnlineGameSceneManager.Instance
                : FindObjectOfType<PhotonOnlineGameSceneManager>();
        }

        if (gamePhaseManager == null)
        {
            gamePhaseManager = FindObjectOfType<GamePhaseManager>();
        }

        if (waveManager == null)
        {
            waveManager = FindObjectOfType<WaveManager>();
        }

        if (playerManager == null)
        {
            playerManager = FindObjectOfType<PlayerManager>();
        }
    }

    /// <summary>
    /// Rebuilds spawner registry from current scene objects or synchronized data.
    /// </summary>
    private void RebuildSpawnerRegistry()
    {
        spawnersById.Clear();
        EnemySpawner[] spawners = waveManager != null && waveManager.spawners != null
            ? waveManager.spawners
            : FindObjectsOfType<EnemySpawner>();

        foreach (EnemySpawner spawner in spawners)
        {
            if (spawner == null || string.IsNullOrWhiteSpace(spawner.name))
            {
                continue;
            }

            if (!spawnersById.ContainsKey(spawner.name))
            {
                spawnersById.Add(spawner.name, spawner);
                continue;
            }

            Debug.LogWarning("Invalid room state: duplicate online enemy spawnPointId found: " + spawner.name);
        }
    }

    /// <summary>
    /// Looks up the target for spawner and applies the resolved gameplay result.
    /// </summary>
    private EnemySpawner ResolveSpawner(string spawnPointId)
    {
        if (spawnersById.Count == 0)
        {
            RebuildSpawnerRegistry();
        }

        spawnersById.TryGetValue(spawnPointId, out EnemySpawner spawner);
        return spawner;
    }

    /// <summary>
    /// Looks up the target for castle by player ID and applies the resolved gameplay result.
    /// </summary>
    private CastleBase ResolveCastleByPlayerId(int playerId)
    {
        CastleBase[] castles = FindObjectsOfType<CastleBase>();

        foreach (CastleBase castle in castles)
        {
            if (castle != null && castle.GetOwnerPlayerId() == playerId)
            {
                return castle;
            }
        }

        return null;
    }

    /// <summary>
    /// Shows online toast with the correct current context.
    /// </summary>
    private void ShowOnlineToast(string message)
    {
        if (onlineGameSceneManager != null)
        {
            onlineGameSceneManager.ShowOnlineToast(message);
            return;
        }

        Debug.Log(message);
    }

    private void RaiseToAll<T>(byte eventCode, T payload)
    {
#if PHOTON_UNITY_NETWORKING
        PhotonNetwork.RaiseEvent(
            eventCode,
            JsonUtility.ToJson(payload),
            new RaiseEventOptions { Receivers = ReceiverGroup.All },
            new SendOptions { Reliability = true }
        );
#endif
    }

    /// <summary>
    /// Checks whether run online wave sync is allowed before enabling that action.
    /// </summary>
    private bool CanRunOnlineWaveSync()
    {
#if PHOTON_UNITY_NETWORKING
        return initialized ||
            (PhotonOnlineGameSceneManager.IsLiveOnlineGameSceneContext() &&
             PhotonNetwork.InRoom &&
             !PhotonNetwork.OfflineMode &&
             PhotonNetwork.CurrentRoom != null);
#else
        return false;
#endif
    }
}

[System.Serializable]
public class OnlineWaveStartData
{
    public int round;
    public int waveIndex;
    public int enemyCount;
    public List<OnlineEnemySpawnData> spawnEntries = new List<OnlineEnemySpawnData>();
}

[System.Serializable]
public class OnlineEnemySpawnData
{
    public string enemyId;
    public string enemyTypeId;
    public string spawnPointId;
    public int spawnOrder;
    public float spawnTime;
}

[System.Serializable]
public class OnlineEnemyPositionBatchData
{
    public int round;
    public int waveIndex;
    public List<OnlineEnemyPositionData> enemies = new List<OnlineEnemyPositionData>();
}

[System.Serializable]
public class OnlineEnemyPositionData
{
    public string enemyId;
    public float x;
    public float y;
    public float z;
}

[System.Serializable]
public class OnlineEnemyHealthData
{
    public string enemyId;
    public string enemyTypeId;
    public int currentHP;
    public int maxHP;
    public int damage;
    public int damageOwnerPlayerId;
    public int round;
    public int waveIndex;
}

[System.Serializable]
public class OnlineEnemyKilledData
{
    public string enemyId;
    public string enemyTypeId;
    public int rewardPlayerId;
    public int round;
    public int waveIndex;
}

[System.Serializable]
public class OnlineCastleDamageData
{
    public int targetPlayerId;
    public int currentHP;
    public int maxHP;
    public int damage;
    public int round;
    public int waveIndex;
}

[System.Serializable]
public class OnlineRewardData
{
    public int rewardPlayerId;
    public int gold;
    public int score;
    public int round;
    public int waveIndex;
}

[System.Serializable]
public class OnlineWaveEndData
{
    public int round;
    public int waveIndex;
    public int nextRound;
}
